### ISSUE TITLE
Native apple m1 (arm64) version?

### ISSUE THREAD

**Issue by thtliife** [ServiceNow/servicenow-cli#3]
Is there any chance of you guys compiling this for apple m1 (arm64) cpus instead of relying on rosetta to emulate x86_64?

**Comment by chiarnglin** [comment]
Unfortunately not in the near term. 
You can try submitting an [IDEA on the portal](https://community.servicenow.com/community?id=ideas_list&sysparm_module_id=enhancement_requests) and get more votes on it.

**Comment by thtliife** [comment]
what about open sourcing it?
Then I can compile it myself)?

**Comment by chiarnglin** [comment]
Not currently in the plans, but I'll bring it up with the team.
